"""initial schema

Revision ID: 5ab09f26fdeb
Revises: 
Create Date: 2026-06-17 19:42:55.157666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab09f26fdeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_tutores_id'), 'tutores', ['id'], unique=False)
    op.create_table('animais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animais_id'), 'animais', ['id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('vacinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_aplicacao', sa.DateTime(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacinas_id'), 'vacinas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacinas_id'), table_name='vacinas')
    op.drop_table('vacinas')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_animais_id'), table_name='animais')
    op.drop_table('animais')
    op.drop_index(op.f('ix_tutores_id'), table_name='tutores')
    op.drop_table('tutores')
    # ### end Alembic commands ###
