"""reset_total

Revision ID: a2727cf69c65
Revises: 
Create Date: 2026-06-19 23:23:39.916590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2727cf69c65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutores_id'), table_name='tutores')
    op.drop_table('tutores')
    op.drop_index(op.f('ix_vacinas_id'), table_name='vacinas')
    op.drop_table('vacinas')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_animais_id'), table_name='animais')
    op.drop_table('animais')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animais',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('animais_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('especie', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name='animais_tutor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='animais_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_animais_id'), 'animais', ['id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], name=op.f('consultas_animal_id_fkey')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('consultas_tutor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consultas_pkey'))
    )
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('vacinas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data_aplicacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('lote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animais.id'], name=op.f('vacinas_animal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vacinas_pkey'))
    )
    op.create_index(op.f('ix_vacinas_id'), 'vacinas', ['id'], unique=False)
    op.create_table('tutores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tutores_pkey')),
    sa.UniqueConstraint('email', name=op.f('tutores_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tutores_id'), 'tutores', ['id'], unique=False)
    # ### end Alembic commands ###
